### PR TITLE
'NoneType' object has no attribute 'SMALL_ICON_SIZE'

### LINKED ISSUE #65: RuntimeError: sys.meta_path must be a list of import hooks, AttributeError: 'NoneType' object has no attribute 'SMALL_ICON_SIZE'
On Fedora 18 on an XO-4 with Sugar 0.112, the Turtle Blocks 218 logs this on stop;

```text
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sugar3/logger.py", line 72, in _except_
    from IPython.ultraTB import AutoFormattedTB
RuntimeError: sys.meta_path must be a list of import hooks

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sugar3/graphics/icon.py", line 559, in 
ferred_height
    self._sync_image_properties()
  File "/usr/lib/python2.7/site-packages/sugar3/graphics/icon.py", line 536, in 
e_properties
    pixel_size = style.SMALL_ICON_SIZE
AttributeError: 'NoneType' object has no attribute 'SMALL_ICON_SIZE'
```

No apparent impact.

No other activities log this.

A bisection shows regression introduced by e3f8fa9 _GTK3 and GST1.0 port_.

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
The PR should fix #65 . This is based on a regression made by e3f8fa9.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Please tell me more about how this solves?

**Comment by Saumya-Mishra9129** [comment]
> Thanks. Please tell me more about how this solves?

As specified in #80 we are getting NoneType error on style object. It means it is not imported by system at the time when you tested. We can see in  e3f8fa9 that the change I made in 
4a3cf3f was removed in e3f8fa9.

**Comment by chimosky** [comment]
@Saumya-Mishra9129 4a3cf3f uses a `try except` clause that imports or sets `GRID_CELL_SIZE`, the issue is with `style.SMALL_ICON_SIZE`.

**Comment by quozl** [comment]
@Saumya-Mishra9129 wrote:
> As specified in #80 

Actually, you mean in https://github.com/sugarlabs/turtleart-activity/issues/65.

> we are getting NoneType error on style object.

Yes.  In the toolkit source file src/sugar3/graphics/icon.py.

`style` was an imported module, as shown by

https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/f0b479f068804db6ab99f38eb79d301fa4580c61/src/sugar3/graphics/icon.py#L106

`style` was found to be None at the point of the error, which was;

https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/f0b479f068804db6ab99f38eb79d301fa4580c61/src/sugar3/graphics/icon.py#L536

Above code links are from Sugar 0.112.

No code changes `style` between the import and the error.

We are also getting a _RuntimeError: sys.meta_path must be a list of import hooks_.

> It means it is not imported by system at the time when you tested.

Not so.  Firstly, it was imported as shown above, and secondly if it were not imported the error would have been "_NameError: name 'style' is not defined_".

> We can see in [e3f8fa9](https://github.com/sugarlabs/turtleart-activity/commit/e3f8fa9d69041f4912fce5f624397c82018a8ffb) that the change I made in [4a3cf3f](https://github.com/sugarlabs/turtleart-activity/commit/4a3cf3fa340c4db1163c3bbedbab8b7fce8c2383) was removed in [e3f8fa9](https://github.com/sugarlabs/turtleart-activity/commit/e3f8fa9d69041f4912fce5f624397c82018a8ffb).

I see your logic; you are suggesting that the port to GTK 3 and GStreamer 1.0, which removed support for very old versions of the GTK 2 toolkit (before GRID_CELL_SIZE was added), was the cause of the error.  You are suggesting that adding back support for very old versions of the GTK 2 toolkit will fix it.   However, the error is not reported against the source file you are changing.

Let me offer an alternative speculation;
* for `style` object to lose meaning in the scope of icon.py, despite being imported, means that the Python data structures in memory have been corrupted,
* for `sys.meta_path` to lose contents in the scope of logger.py, means that the Python data structures in memory have been corrupted,
* that the code was ported from GTK 2 with static modules to GTK 3 with PyGObject introspection modules suggests that the actual changes in Turtle Art https://github.com/sugarlabs/turtleart-activity/commit/e3f8fa9d69041f4912fce5f624397c82018a8ffb may be less important than the changes between GTK 2 and GTK 3, and between static imports and PyGObject introspection imports.

By the way, to reproduce or test this you would need to install Fedora 18 VM with Sugar 0.112 packages.  Those packages are available for i386 32-bit architecture from rpmdropbox.laptop.org.

**Comment by Saumya-Mishra9129** [comment]
> @Saumya-Mishra9129 wrote:
> 
> > As specified in #80
> 
> Actually, you mean in #65.
> 
> > we are getting NoneType error on style object.
> 
> Yes. In the toolkit source file src/sugar3/graphics/icon.py.
> 
> `style` was an imported module, as shown by
> 
> https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/f0b479f068804db6ab99f38eb79d301fa4580c61/src/sugar3/graphics/icon.py#L106
> 
> `style` was found to be None at the point of the error, which was;
> 
> https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/f0b479f068804db6ab99f38eb79d301fa4580c61/src/sugar3/graphics/icon.py#L536
> 
> Above code links are from Sugar 0.112.
> 
> No code changes `style` between the import and the error.
> 
> We are also getting a _RuntimeError: sys.meta_path must be a list of import hooks_.
> 
> > It means it is not imported by system at the time when you tested.
> 
> Not so. Firstly, it was imported as shown above, and secondly if it were not imported the error would have been "_NameError: name 'style' is not defined_".
> 
> > We can see in [e3f8fa9](https://github.com/sugarlabs/turtleart-activity/commit/e3f8fa9d69041f4912fce5f624397c82018a8ffb) that the change I made in [4a3cf3f](https://github.com/sugarlabs/turtleart-activity/commit/4a3cf3fa340c4db1163c3bbedbab8b7fce8c2383) was removed in [e3f8fa9](https://github.com/sugarlabs/turtleart-activity/commit/e3f8fa9d69041f4912fce5f624397c82018a8ffb).
> 
> I see your logic; you are suggesting that the port to GTK 3 and GStreamer 1.0, which removed support for very old versions of the GTK 2 toolkit (before GRID_CELL_SIZE was added), was the cause of the error. You are suggesting that adding back support for very old versions of the GTK 2 toolkit will fix it. However, the error is not reported against the source file you are changing.
> 
> Let me offer an alternative speculation;
> 
> * for `style` object to lose meaning in the scope of icon.py, despite being imported, means that the Python data structures in memory have been corrupted,
> * for `sys.meta_path` to lose contents in the scope of logger.py, means that the Python data structures in memory have been corrupted,
> * that the code was ported from GTK 2 with static modules to GTK 3 with PyGObject introspection modules suggests that the actual changes in Turtle Art [e3f8fa9](https://github.com/sugarlabs/turtleart-activity/commit/e3f8fa9d69041f4912fce5f624397c82018a8ffb) may be less important than the changes between GTK 2 and GTK 3, and between static imports and PyGObject introspection imports.
> 
> By the way, to reproduce or test this you would need to install Fedora 18 VM with Sugar 0.112 packages. Those packages are available for i386 32-bit architecture from rpmdropbox.laptop.org.

Yeah You are probably right. however I think sugar-toolkit-gtk3 is the place which can cause the error because of port from GTK2 to GTK3 . I still need to test it on Fedora because we can't make assumptions.
