### ISSUE TITLE
RuntimeError: sys.meta_path must be a list of import hooks, AttributeError: 'NoneType' object has no attribute 'SMALL_ICON_SIZE'

### ISSUE THREAD

**Issue by quozl** [sugarlabs/turtleart-activity#65]
On Fedora 18 on an XO-4 with Sugar 0.112, the Turtle Blocks 218 logs this on stop;

```text
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sugar3/logger.py", line 72, in _except_
    from IPython.ultraTB import AutoFormattedTB
RuntimeError: sys.meta_path must be a list of import hooks

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sugar3/graphics/icon.py", line 559, in 
ferred_height
    self._sync_image_properties()
  File "/usr/lib/python2.7/site-packages/sugar3/graphics/icon.py", line 536, in 
e_properties
    pixel_size = style.SMALL_ICON_SIZE
AttributeError: 'NoneType' object has no attribute 'SMALL_ICON_SIZE'
```

No apparent impact.

No other activities log this.

A bisection shows regression introduced by e3f8fa9 _GTK3 and GST1.0 port_.

**Comment by manvirsingh01** [comment]
Hello! I want to work on this problem. According to what I've observed, there are two distinct mistakes here:
**First Error:** 
AttributeError In sugar3/graphics/icon.py, the 'NoneType' object lacks the attribute 'SMALL_ICON_SIZE'.
When the code attempts to use the style object, it appears to be None. This could indicate that the style is not being loaded or initialized correctly. Adding a check before accessing style could be a solution.To facilitate debugging, load a default style or display a more understandable error message if SMALL_ICON_SIZE is None.
**Error number two:**
RuntimeError: sugar3/logger.py's sys.meta_path must be a list of import hooks
The way sys.meta_path is handled appears to be connected to this. Something might be altering it in a way that makes it incompatible with the Python/IPython environment as it stands right now. To make sure that sys.meta_path is always a correct list, I want to examine how it is configured in the logger and make the necessary adjustments.
I am certain that I can work on both of these and offer a solution. Would you kindly assign me the problem?
